version: '3.5'

services:
  neo4j:
    image: neo4j:4.1
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
      -  NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ./neo4j/plugins:/plugins

  mongo:
    image: mongo:4.0
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/dump:/dump
      - ./mongo/dump/init.sh:/docker-entrypoint-initdb.d/init.sh

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081

  neodash:
    image: nielsdejong/neodash
    ports:
      - 5005:5005
    depends_on:
     - neo4j
