version: '3.5'

services:
  neo4j:
    image: neo4j:4.1
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
      -  NEO4JLABS_PLUGINS=["apoc"]
      -  NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      -  NEO4J_dbms_memory_pagecache_size=1G
      -  NEO4J_server_memory_heap_max__size=1G
    volumes:
      - ./neo4j/plugins:/plugins
      - neo4j-data:/data

  mongo:
    image: mongo:4.0
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081

  mongo-init:
    build: 
      context: .
      dockerfile: Dockerfile.pandas-init
    container_name: mongo-init
    volumes:
      - ./mongo/node/dataset:/app/dataset
      - ./mongo/node/init.py:/app/init.py
      - ./mongo/node/main.py:/app/main.py
      - ./mongo/node/mapcsv.py:/app/mapcsv.py
    depends_on:
      - mongo

  notebook:
    container_name: notebook
    build:
      context: .
      dockerfile: Dockerfile.notebook
    ports:
      - 1000:8888
    volumes:
      - ./neo4j/notebook:/home/jovyan/work
    depends_on:
      - neo4j

volumes:
  mongo-volume:
  neo4j-data: